spring.application.name=backend

# \BASE DE DONNÉES
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d7tlescm0tmc73cstoeg-a/transport_tunis}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:transport_tunis_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:J1i3b1bZsNIBSARdaY60Nh2XVsiVPKw1}
spring.datasource.driver-class-name=org.postgresql.Driver

# \ JPA 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# \PORT 
server.port=${PORT:10000}

# \SÉCURITÉ 
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.security.user.password=disabled

# \MAIL 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=transport.platform.tn@gmail.com
spring.mail.password=ufxfwschmexqsmmg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# \JWT
jwt.secret=transportTNSecretKey2025
jwt.expiration=86400000