spting.application.name=backend 
spring.datasource.url=jdbc:postgresql://localhost:5432/transport_tunis?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=nejah123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8085
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration  
spring.security.enabled=false
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=transport.platform.tn@gmail.com
spring.mail.password=ufxfwschmexqsmmg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.security.user.password=disabled