spting.application.name=backend 
spring.datasource.url=jdbc:postgresql://dpg-d7tlescm0tmc73cstoeg-a.oregon-postgres.render.com/transport_tunis
spring.datasource.username=transport_tunis_user
spring.datasource.password=J1i3b1bZsNIBSARdaY60Nh2XVsiVPKw1
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8085}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration  
spring.security.enabled=false
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=transport.platform.tn@gmail.com
spring.mail.password=ufxfwschmexqsmmg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.security.user.password=disabled
spring.jpa.hibernate.ddl-auto=update
jwt.secret=transportTNSecretKey2025
jwt.expiration=86400000